### ISSUE TITLE
Centered images when using CircleList 

### ISSUE THREAD

**Issue by salihyalcin** [dkmeteor/CircleList#1]
Hello, 

First of all thaks for sharing amazing app providing this functionality. I have 2 question. I am curious about code below. Which stuff do this code ? I attached my drawing. So I tried to change your calculatescale function but couldn't afford. Could you help me ?

Thanks

```
 private float calcuylateScale(int top, int h) {
        float result = 0f;

        result = (1f - 1f/2f*Math.abs((top - h / 2f)) / (h / 2f)) * fullScaleFactor;
        return result;

    }
```

![xx](https://cloud.githubusercontent.com/assets/9201717/20927619/1125f14a-bbcb-11e6-9267-dbbc3ac434b7.png)

**Comment by dkmeteor** [comment]
factor = Math.abs((top - h / 2f)) / (h / 2f)

It means the distance from "the view" to "center of screen"
when the view is at the center of screen , factor = 0.
when the view is at the top or bottom of screen, factor = 1

---

result  = 1 - 0.5*factor * fullScaleFactor

0.5 is  max scale factor.
when view is at the top of screen , it view scale to 50%
when view is at the center of screen , it will scale to 100%
